services:
  - type: static_site
    name: crafted-web-frontend
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm run build
    publishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production