services:
  - type: web
    name: crafted-web-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://your-api-url.com